name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    env:
      MSYS2_PATH_TYPE: inherit
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: false
          release: false
          install: >-
            ninja

      - name: Build
        run: |
          .github/scripts/setenv.ps1
          ninja -C build shim.exe
